FromLake simplest approach using Q-learning. 

In [1]:
import gym 
import numpy as np 

Intialize the FrozenLake Environment 

In [2]:
env = gym.make("FrozenLake-v1", is_slippery=True)

Initialize the Q-tables with zeros. <br/>
Q-table has dimensions -> (number_of_states, number_of_actions)

In [3]:
Q = np.zeros((env.observation_space.n, env.action_space.n))

In [4]:
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

This is because number of observation space is 16, as frozen lake is 4*4 matrix. And number of action space is 4. Up, Down, Left, Right. 

Next we define the hyoerparameters.

In [5]:
learning_rate = 0.8 # How much we learn from the new information 
discount_factor = 0.95 # How much we consider the future rewards
epsilon = 0.1 # Exploration rate 
epsilon_decay = 0.995 # Decay Rate for the exploration 
min_epsilon = 0.01 # Minimum exploration rate 
episodes = 2000 # Minimum number of episodes to train 

Next we write the Q-learning algorithm.

In [6]:
for episodes in range(episodes):
    state = env.reset() # Reset environment for the each episode 
    done = False # Track if the episode is finished
    while not done:
        # Exploratiion - Exploitation trade off: choose random or best action 
        if np.random.uniform(0,1) < epsilon:
            action = env.action_space.sample() # Explore: choose random action 
        else:
            action = np.argmax(Q[state, :]) # Exploit: Choose the best action from Q-table 

        # Take action, observe new state and reward  
        next_state, reward, done, _ = env.step(action)

        # Update Q-value using the Q-learning formula 
        Q[state, action] = Q[state, action] + learning_rate * (reward + discount_factor * np.max(Q[next_state: ]) - Q[state, action])

        # Move to the next state 
        state = next_state 

    # Decay epsilon after each step 
    epsilon = min(min_epsilon, epsilon * epsilon_decay)

# Print final value after the training 
print("Final Q-table.")
print(Q)

# Test the trained agent 
test_episode = 5
for episode in range(test_episode):
    state = env.reset() # Reset ebvironment for the testing 
    done = False 
    print(f"\nEpisode {episode + 1}")
    while not done:
        env.render() # Visualize the environment 
        action = np.argmax(Q[state, :]) # Take the action with the highest value 
        next_state, reward, done, _ = env.step(action)
        state = next_state
        if done:
            if reward == 1:
                print("Reached the goal!")
            else:
                print("Fell into hole.")
env.close() # Close the environment 

Final Q-table.
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Episode 1
Fell into hole.

Episode 2
Fell into hole.

Episode 3
Fell into hole.

Episode 4
Fell into hole.

Episode 5
Fell into hole.
